create table persons (
	id 	BIGSERIAL PRIMARY KEY NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(50),
	gender VARCHAR(50),
	date_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(100) NOT NULL
);
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (1, 'Ericha', 'Hawtry', 'ehawtry0@macromedia.com', 'Female', '10/20/1976', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (2, 'Ezra', 'McClenan', 'emcclenan1@pen.io', 'Male', '7/16/1998', 'Japan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (3, 'Lester', 'Howgill', null, 'Male', '10/9/2004', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (4, 'Tilda', 'Riggott', 'triggott3@about.com', 'Female', '9/30/2000', 'Haiti');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (5, 'Pippo', 'Warren', null, 'Agender', '2/18/1982', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (6, 'Gayla', 'Aldrich', null, 'Female', '10/8/1947', 'Cuba');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (7, 'Gordon', 'Mahood', 'gmahood6@nytimes.com', 'Male', '9/25/1998', 'Mongolia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (8, 'Meridel', 'McPartlin', 'mmcpartlin7@scribd.com', 'Female', '11/27/1966', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (9, 'Tades', 'Marde', 'tmarde8@theguardian.com', 'Male', '11/16/1945', 'Brazil');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (10, 'Tyrus', 'Vell', null, 'Male', '2/12/1997', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (11, 'Blanca', 'Waycot', 'bwaycota@elpais.com', 'Female', '12/11/2021', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (12, 'Daisi', 'Stansell', 'dstansellb@sciencedaily.com', 'Female', '3/4/1981', 'Brazil');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (13, 'Herbert', 'Duckerin', 'hduckerinc@bbb.org', 'Male', '5/1/1988', 'Zimbabwe');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (14, 'Marya', 'Parfitt', 'mparfittd@house.gov', 'Non-binary', '1/31/2009', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (15, 'Alexandre', 'McGlashan', 'amcglashane@google.ca', 'Male', '5/28/2002', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (16, 'Ann', 'Tench', 'atenchf@jugem.jp', 'Female', '7/24/1990', 'Albania');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (17, 'Abbie', 'Rappa', 'arappag@bigcartel.com', 'Male', '7/9/2002', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (18, 'Dinny', 'Tackett', 'dtacketth@forbes.com', 'Female', '5/6/2010', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (19, 'Bendick', 'Bassham', 'bbasshami@rakuten.co.jp', 'Male', '10/1/2010', 'Poland');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (20, 'Xerxes', 'Seeborne', null, 'Male', '4/29/2001', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (21, 'Arabelle', 'Edsall', null, 'Female', '9/13/2020', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (22, 'Marlane', 'Cortes', 'mcortesl@imageshack.us', 'Bigender', '5/14/1990', 'United States');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (23, 'Beverlee', 'Thursby', 'bthursbym@blog.com', 'Female', '11/10/1960', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (24, 'Valida', 'Rilston', null, 'Female', '9/9/1968', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (25, 'Scottie', 'Waddoups', 'swaddoupso@exblog.jp', 'Male', '5/13/1968', 'Bangladesh');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (26, 'Miguel', 'Greenleaf', null, 'Male', '7/27/1952', 'Portugal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (27, 'Ber', 'Lashbrook', 'blashbrookq@friendfeed.com', 'Male', '4/14/1966', 'Kazakhstan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (28, 'Johannah', 'Gravenell', null, 'Female', '4/30/1953', 'France');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (29, 'Willi', 'Maidlow', null, 'Female', '5/29/1995', 'Ireland');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (30, 'Aldus', 'O''Kane', 'aokanet@epa.gov', 'Male', '8/2/2013', 'Slovenia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (31, 'Maryann', 'Vigneron', 'mvigneronu@privacy.gov.au', 'Female', '12/3/1972', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (32, 'Christophe', 'Braunstein', 'cbraunsteinv@wunderground.com', 'Male', '11/26/1997', 'Ukraine');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (33, 'Ebeneser', 'Pilbeam', 'epilbeamw@constantcontact.com', 'Male', '9/14/2021', 'Canada');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (34, 'Zackariah', 'Manners', 'zmannersx@unblog.fr', 'Male', '12/7/1972', 'Burkina Faso');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (35, 'Bryn', 'Sonley', null, 'Female', '11/18/1947', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (36, 'Murdock', 'Litchfield', null, 'Male', '6/17/2001', 'Panama');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (37, 'Kale', 'Dunphy', 'kdunphy10@wikimedia.org', 'Male', '2/15/1989', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (38, 'Melissa', 'Braghini', null, 'Female', '2/28/1982', 'Greece');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (39, 'Tootsie', 'Jonson', 'tjonson12@360.cn', 'Female', '2/15/1982', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (40, 'Odell', 'Whitelaw', null, 'Male', '1/9/1948', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (41, 'Eba', 'Terzza', 'eterzza14@example.com', 'Female', '4/29/1993', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (42, 'Guenna', 'Gheorghie', 'ggheorghie15@ezinearticles.com', 'Female', '1/7/1997', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (43, 'Kalle', 'Lettsom', 'klettsom16@addtoany.com', 'Male', '8/31/1970', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (44, 'Orelie', 'Sowersby', null, 'Female', '2/4/1984', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (45, 'Agnola', 'Diprose', 'adiprose18@yahoo.com', 'Female', '9/23/1974', 'Canada');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (46, 'Verine', 'Dominguez', 'vdominguez19@buzzfeed.com', 'Female', '10/18/2020', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (47, 'Jerrold', 'Thomel', 'jthomel1a@marketwatch.com', 'Male', '12/31/1949', 'Poland');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (48, 'Thea', 'Bendik', 'tbendik1b@ted.com', 'Female', '4/9/2007', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (49, 'Nicolea', 'Helliker', 'nhelliker1c@mapquest.com', 'Female', '1/17/1945', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (50, 'Piotr', 'Bunney', 'pbunney1d@usa.gov', 'Male', '6/14/1993', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (51, 'Amelia', 'Tregear', 'atregear1e@rediff.com', 'Female', '6/14/2005', 'Bulgaria');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (52, 'Reinaldos', 'Pauncefort', 'rpauncefort1f@unesco.org', 'Male', '2/4/2009', 'Egypt');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (53, 'Rowan', 'Bleyman', 'rbleyman1g@taobao.com', 'Male', '3/10/2009', 'Czech Republic');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (54, 'Corby', 'Gaffey', 'cgaffey1h@mayoclinic.com', 'Non-binary', '5/21/1990', 'Palestinian Territory');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (55, 'Norma', 'Marcam', null, 'Female', '2/1/1999', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (56, 'Elana', 'Krol', 'ekrol1j@yahoo.co.jp', 'Female', '10/24/1999', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (57, 'Timmi', 'O''Hannen', 'tohannen1k@etsy.com', 'Female', '11/16/1998', 'Dominican Republic');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (58, 'Inness', 'Hiseman', 'ihiseman1l@bbc.co.uk', 'Male', '9/2/1974', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (59, 'Garvey', 'Braunlein', 'gbraunlein1m@odnoklassniki.ru', 'Male', '8/12/1963', 'Argentina');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (60, 'Jordana', 'Espadero', null, 'Female', '10/22/1955', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (61, 'Hedi', 'Gellier', 'hgellier1o@jimdo.com', 'Female', '12/1/1970', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (62, 'Lucienne', 'Kilgrew', 'lkilgrew1p@livejournal.com', 'Female', '10/25/1994', 'Oman');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (63, 'Anatola', 'Gofford', 'agofford1q@diigo.com', 'Female', '5/16/1965', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (64, 'Isaac', 'Paquet', 'ipaquet1r@geocities.jp', 'Male', '7/29/1977', 'Colombia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (65, 'Maisie', 'Walkley', 'mwalkley1s@miitbeian.gov.cn', 'Female', '3/16/2021', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (66, 'Leda', 'Fullalove', 'lfullalove1t@google.de', 'Female', '8/25/1990', 'Italy');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (67, 'Wenda', 'McLenahan', null, 'Female', '4/1/2004', 'Dominican Republic');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (68, 'Rudolfo', 'Tallboy', null, 'Male', '9/30/1962', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (69, 'Krisha', 'Luciani', 'kluciani1w@ebay.co.uk', 'Male', '6/16/1951', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (70, 'Kristofer', 'Goodson', null, 'Male', '2/12/1976', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (71, 'Germana', 'Devonshire', null, 'Female', '9/10/1950', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (72, 'Burgess', 'Smithers', 'bsmithers1z@cam.ac.uk', 'Bigender', '1/20/2004', 'Gabon');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (73, 'Jedidiah', 'Nassie', null, 'Male', '9/18/1947', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (74, 'Evanne', 'Hutcheon', 'ehutcheon21@taobao.com', 'Female', '8/23/2004', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (75, 'Donny', 'Gockelen', 'dgockelen22@alexa.com', 'Male', '8/22/2021', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (76, 'Amberly', 'Payle', 'apayle23@unesco.org', 'Female', '12/9/1956', 'Peru');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (77, 'Cale', 'Speariett', 'cspeariett24@springer.com', 'Male', '8/14/2020', 'Canada');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (78, 'Cherri', 'Nuttey', 'cnuttey25@examiner.com', 'Female', '10/25/2005', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (79, 'Stella', 'Szanto', 'sszanto26@reference.com', 'Female', '2/19/1999', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (80, 'Ferne', 'Cameron', 'fcameron27@eepurl.com', 'Genderqueer', '1/10/2023', 'Uzbekistan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (81, 'Sande', 'Tawton', null, 'Female', '4/25/1982', 'United States');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (82, 'Jordon', 'Noorwood', 'jnoorwood29@discuz.net', 'Male', '4/20/1995', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (83, 'Waring', 'Burgen', null, 'Male', '11/25/2014', 'Portugal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (84, 'Persis', 'Cornuau', null, 'Female', '10/5/2022', 'Argentina');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (85, 'Lamar', 'Jamme', 'ljamme2c@patch.com', 'Male', '12/3/1981', 'Greece');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (86, 'Dore', 'Wishart', 'dwishart2d@yolasite.com', 'Female', '11/20/1967', 'Slovenia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (87, 'Shepherd', 'Webben', 'swebben2e@addthis.com', 'Male', '10/29/2020', 'Argentina');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (88, 'Berke', 'Heino', 'bheino2f@dell.com', 'Male', '1/15/1978', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (89, 'Vale', 'Cattrall', 'vcattrall2g@newsvine.com', 'Female', '2/7/1988', 'Brazil');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (90, 'Virgie', 'Teek', 'vteek2h@nyu.edu', 'Male', '1/31/1978', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (91, 'Elton', 'Otridge', 'eotridge2i@ibm.com', 'Male', '1/17/1991', 'Spain');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (92, 'Codi', 'Bony', 'cbony2j@furl.net', 'Female', '8/27/1956', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (93, 'Kelly', 'Ganforthe', 'kganforthe2k@npr.org', 'Polygender', '12/1/1965', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (94, 'Georgeanna', 'Hornig', 'ghornig2l@storify.com', 'Female', '9/13/1982', 'Cyprus');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (95, 'Ortensia', 'Donaher', 'odonaher2m@hatena.ne.jp', 'Female', '2/11/2018', 'Japan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (96, 'Ahmad', 'Grzelewski', null, 'Male', '6/6/1953', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (97, 'Tyrus', 'Mellmer', 'tmellmer2o@time.com', 'Male', '7/18/1953', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (98, 'Fitz', 'Fromant', 'ffromant2p@alibaba.com', 'Male', '5/12/1988', 'Peru');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (99, 'Flss', 'Crohan', 'fcrohan2q@intel.com', 'Female', '6/13/1987', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (100, 'Sandi', 'Bathow', null, 'Female', '7/11/2011', 'Russia');

