create table persons (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	gender VARCHAR(50) NOT NULL,
	date_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(50) NOT NULL
);
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (1, 'Omero', 'Lownds', 'olownds0@sourceforge.net', 'Male', '5/6/2023', 'Canada');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (2, 'Sherrie', 'Colclough', 'scolclough1@upenn.edu', 'Female', '11/20/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (3, 'Far', 'Lamprecht', 'flamprecht2@github.com', 'Male', '9/21/2023', 'Pakistan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (4, 'Itch', 'Matveiko', 'imatveiko3@dropbox.com', 'Male', '9/26/2023', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (5, 'Kirby', 'Suche', 'ksuche4@ed.gov', 'Agender', '2/26/2023', 'France');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (6, 'Shelley', 'Ensor', 'sensor5@pen.io', 'Male', '3/20/2023', 'France');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (7, 'Darcee', 'Pavlitschek', 'dpavlitschek6@addtoany.com', 'Genderqueer', '2/12/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (8, 'Lira', 'Isham', 'lisham7@cmu.edu', 'Female', '3/7/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (9, 'Adolpho', 'Houchen', 'ahouchen8@soundcloud.com', 'Male', '9/3/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (10, 'Iona', 'Rastall', 'irastall9@wikispaces.com', 'Female', '11/30/2023', 'France');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (11, 'Will', 'McAnulty', null, 'Male', '11/3/2023', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (12, 'Hashim', 'Gilchriest', 'hgilchriestb@nasa.gov', 'Male', '2/5/2023', 'Brazil');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (13, 'Ive', 'Amdohr', 'iamdohrc@mozilla.com', 'Male', '2/1/2023', 'Ukraine');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (14, 'Matthaeus', 'Bufton', 'mbuftond@theatlantic.com', 'Agender', '6/17/2023', 'Afghanistan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (15, 'Aggy', 'Gillogley', 'agillogleye@cbslocal.com', 'Female', '4/20/2023', 'Guinea');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (16, 'Ag', 'Theodoris', 'atheodorisf@mtv.com', 'Female', '8/18/2023', 'Yemen');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (17, 'Rhianna', 'Hansbury', 'rhansburyg@mysql.com', 'Female', '11/16/2023', 'Croatia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (18, 'Calv', 'Jonas', 'cjonash@whitehouse.gov', 'Male', '9/25/2023', 'Nepal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (19, 'Nathanael', 'Trevino', 'ntrevinoi@clickbank.net', 'Male', '11/14/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (20, 'Valdemar', 'Bowling', 'vbowlingj@yahoo.com', 'Male', '9/25/2023', 'Brazil');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (21, 'Sholom', 'Normaville', 'snormavillek@go.com', 'Male', '3/17/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (22, 'Thaddus', 'Kilbane', 'tkilbanel@macromedia.com', 'Male', '7/31/2023', 'Guatemala');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (23, 'Fletch', 'Jobbing', 'fjobbingm@4shared.com', 'Male', '9/26/2023', 'Morocco');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (24, 'Boothe', 'Gillum', 'bgillumn@indiatimes.com', 'Male', '1/1/2024', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (25, 'Oliviero', 'Orrill', 'oorrillo@bandcamp.com', 'Agender', '12/29/2023', 'Finland');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (26, 'Lauren', 'Lardeux', 'llardeuxp@disqus.com', 'Female', '11/1/2023', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (27, 'Nikki', 'Denkel', 'ndenkelq@dmoz.org', 'Male', '8/17/2023', 'Moldova');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (28, 'Cory', 'Geddes', 'cgeddesr@com.com', 'Female', '11/14/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (29, 'Consalve', 'McPeake', 'cmcpeakes@army.mil', 'Male', '6/8/2023', 'Portugal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (30, 'Jamesy', 'Vaux', 'jvauxt@free.fr', 'Male', '3/30/2023', 'Cyprus');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (31, 'Petey', 'Purdy', 'ppurdyu@bloomberg.com', 'Male', '1/8/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (32, 'Carlynne', 'Cantle', 'ccantlev@icq.com', 'Female', '5/22/2023', 'Portugal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (33, 'Jermaine', 'Steeden', 'jsteedenw@un.org', 'Male', '2/8/2023', 'Greece');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (34, 'Payton', 'Vost', 'pvostx@altervista.org', 'Male', '5/8/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (35, 'Iago', 'Kimbell', 'ikimbelly@usda.gov', 'Male', '1/7/2023', 'Iraq');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (36, 'Nickola', 'Beynon', 'nbeynonz@loc.gov', 'Bigender', '4/23/2023', 'Portugal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (37, 'Gonzales', 'Raison', 'graison10@thetimes.co.uk', 'Male', '4/22/2023', 'United States');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (38, 'Steward', 'Sheaber', 'ssheaber11@apache.org', 'Male', '2/1/2023', 'Colombia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (39, 'Dennison', 'Marrington', null, 'Male', '8/17/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (40, 'Kessia', 'Juniper', 'kjuniper13@epa.gov', 'Female', '6/13/2023', 'Serbia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (41, 'Lowell', 'Dipple', 'ldipple14@rambler.ru', 'Male', '3/19/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (42, 'Georgianna', 'Fowley', 'gfowley15@pagesperso-orange.fr', 'Female', '5/3/2023', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (43, 'Roseann', 'Guirau', 'rguirau16@amazon.com', 'Female', '12/18/2023', 'South Korea');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (44, 'Claudius', 'Charnick', 'ccharnick17@patch.com', 'Non-binary', '5/3/2023', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (45, 'Robena', 'Snowsill', 'rsnowsill18@shop-pro.jp', 'Female', '9/22/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (46, 'Carmelia', 'Gainor', 'cgainor19@tumblr.com', 'Female', '10/5/2023', 'Japan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (47, 'Tanney', 'Blades', 'tblades1a@samsung.com', 'Male', '5/23/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (48, 'Viole', 'Kennefick', 'vkennefick1b@google.com.br', 'Non-binary', '5/19/2023', 'Finland');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (49, 'Eddie', 'Archibould', 'earchibould1c@npr.org', 'Male', '12/23/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (50, 'Tab', 'Tinan', 'ttinan1d@wikipedia.org', 'Male', '7/10/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (51, 'Rutherford', 'Lewsie', 'rlewsie1e@bizjournals.com', 'Male', '2/20/2023', 'Mongolia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (52, 'Virgilio', 'McKane', 'vmckane1f@hubpages.com', 'Male', '3/24/2023', 'Sweden');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (53, 'Doretta', 'Cheeney', null, 'Female', '7/15/2023', 'Palestinian Territory');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (54, 'Matthias', 'Martino', 'mmartino1h@hexun.com', 'Male', '12/25/2023', 'Costa Rica');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (55, 'Marielle', 'Cotterell', null, 'Genderfluid', '5/25/2023', 'United States');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (56, 'Hillery', 'Petriello', 'hpetriello1j@irs.gov', 'Male', '11/18/2023', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (57, 'Gregorio', 'Havard', 'ghavard1k@jugem.jp', 'Male', '9/5/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (58, 'Wendel', 'Sturley', 'wsturley1l@t-online.de', 'Male', '11/11/2023', 'Dominican Republic');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (59, 'Philomena', 'Kayser', 'pkayser1m@miibeian.gov.cn', 'Female', '4/17/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (60, 'Brendan', 'Quinell', 'bquinell1n@paypal.com', 'Male', '6/15/2023', 'Portugal');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (61, 'Othella', 'Coverley', 'ocoverley1o@godaddy.com', 'Female', '8/16/2023', 'Russia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (62, 'Lucia', 'Daouse', 'ldaouse1p@webnode.com', 'Female', '12/23/2023', 'Thailand');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (63, 'Free', 'Kleimt', 'fkleimt1q@reddit.com', 'Male', '2/13/2023', 'Cuba');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (64, 'Katine', 'Clair', 'kclair1r@theglobeandmail.com', 'Female', '11/25/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (65, 'Abraham', 'Balogh', 'abalogh1s@salon.com', 'Male', '3/5/2023', 'Argentina');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (66, 'Henrietta', 'Frogley', 'hfrogley1t@cdbaby.com', 'Female', '8/12/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (67, 'Dedra', 'Bucky', 'dbucky1u@posterous.com', 'Female', '6/1/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (68, 'Leyla', 'Cregeen', 'lcregeen1v@unblog.fr', 'Female', '11/21/2023', 'Thailand');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (69, 'Gareth', 'Tilson', 'gtilson1w@friendfeed.com', 'Male', '11/21/2023', 'Madagascar');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (70, 'Jackson', 'Lampke', 'jlampke1x@yellowpages.com', 'Male', '4/7/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (71, 'Kristin', 'McGrudder', 'kmcgrudder1y@noaa.gov', 'Female', '12/12/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (72, 'Bron', 'Llopis', 'bllopis1z@earthlink.net', 'Male', '11/1/2023', 'France');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (73, 'Kacey', 'Raycroft', 'kraycroft20@oaic.gov.au', 'Female', '6/22/2023', 'American Samoa');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (74, 'Pippa', 'Fayter', 'pfayter21@baidu.com', 'Female', '3/2/2023', 'Philippines');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (75, 'Sallyanne', 'Theze', 'stheze22@amazon.co.jp', 'Female', '6/17/2023', 'Thailand');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (76, 'Bronny', 'Keenan', 'bkeenan23@goo.gl', 'Male', '1/13/2023', 'Ukraine');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (77, 'Lorne', 'Agglione', 'lagglione24@bandcamp.com', 'Female', '12/23/2023', 'United Kingdom');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (78, 'Roseline', 'Culpin', null, 'Female', '5/28/2023', 'Ivory Coast');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (79, 'Izzy', 'Hugland', 'ihugland26@house.gov', 'Male', '1/31/2023', 'Panama');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (80, 'Ferrel', 'Eldered', 'feldered27@usa.gov', 'Male', '8/24/2023', 'Ethiopia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (81, 'Lori', 'Aime', 'laime28@goo.ne.jp', 'Female', '8/14/2023', 'Democratic Republic of the Congo');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (82, 'Queenie', 'Pace', 'qpace29@scientificamerican.com', 'Female', '12/28/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (83, 'Charil', 'Skeermor', 'cskeermor2a@timesonline.co.uk', 'Female', '6/2/2023', 'Czech Republic');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (84, 'Darrel', 'Aldam', 'daldam2b@ebay.co.uk', 'Male', '10/22/2023', 'Poland');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (85, 'Georgena', 'Thornborrow', 'gthornborrow2c@amazon.com', 'Female', '7/26/2023', 'Uzbekistan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (86, 'Matthus', 'Quogan', 'mquogan2d@prweb.com', 'Male', '1/24/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (87, 'Ginny', 'Coopper', 'gcoopper2e@acquirethisname.com', 'Female', '7/15/2023', 'Libya');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (88, 'Corrie', 'Rushbrooke', 'crushbrooke2f@prnewswire.com', 'Male', '12/5/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (89, 'King', 'Campanelle', 'kcampanelle2g@youku.com', 'Male', '2/1/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (90, 'Hamlin', 'Bigglestone', 'hbigglestone2h@livejournal.com', 'Male', '6/13/2023', 'Belarus');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (91, 'Olympie', 'Dellow', 'odellow2i@sitemeter.com', 'Female', '10/29/2023', 'Pakistan');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (92, 'Elsinore', 'Jesse', 'ejesse2j@drupal.org', 'Female', '11/29/2023', 'Lithuania');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (93, 'Cherianne', 'Isaq', 'cisaq2k@fastcompany.com', 'Female', '6/6/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (94, 'Ray', 'Jobke', null, 'Male', '2/11/2023', 'Argentina');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (95, 'Artemas', 'Jessen', 'ajessen2m@wordpress.org', 'Male', '4/4/2023', 'China');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (96, 'Eddie', 'Debney', 'edebney2n@technorati.com', 'Male', '4/25/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (97, 'Dev', 'Tefft', 'dtefft2o@fema.gov', 'Male', '12/19/2023', 'Brazil');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (98, 'Deirdre', 'Davydoch', 'ddavydoch2p@cbsnews.com', 'Female', '10/13/2023', 'Indonesia');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (99, 'Ainsley', 'Liddel', 'aliddel2q@meetup.com', 'Female', '5/13/2023', 'Nicaragua');
insert into persons (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (100, 'Georgiana', 'Minmagh', 'gminmagh2r@princeton.edu', 'Female', '8/12/2023', 'Indonesia');
